In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df = pd.read_csv(os.path.join("nobetter2.csv"))
df.head()

,2010 Population,% Foreign Born,Median Household Income,Below Poverty Level,% Black-owned Firms,% Asian-owned Firms,% Hispanic-owned Firms,% Women-owned Firms,Retail Sales per Capita,Land Area (Square Miles),...,"('Votes', 'Donald Trump')","('Votes', 'Hillary Clinton')","('Votes', 'Jeb Bush')","('Votes', 'John Kasich')","('Votes', 'Marco Rubio')","('Votes', ""Martin O'Malley"")","('Votes', 'Mike Huckabee')","('Votes', 'Rand Paul')","('Votes', 'Rick Santorum')","('Votes', 'Ted Cruz')"
0,54571,1.6,53682,12.1,15.2,1.3,0.7,31.7,12003,594.44,...,5387,2387,0,421,1785,0,0,0,0,2482
1,182265,3.6,50221,13.9,2.7,1.0,1.3,27.3,17166,1589.78,...,23618,5290,0,2987,9703,0,0,0,0,8571
2,27457,2.9,32911,26.7,0.0,0.0,0.0,27.0,6334,884.88,...,1710,2567,0,123,498,0,0,0,0,609
3,22915,1.2,36447,18.1,14.9,0.0,0.0,0.0,5804,622.58,...,1959,942,0,84,444,0,0,0,0,1011
4,57322,4.3,44145,15.8,0.0,0.0,0.0,23.2,5622,644.78,...,7390,564,0,337,1843,0,0,0,0,3698

In [3]:
df.columns

Index(['2010 Population', '% Foreign Born', 'Median Household Income',
       'Below Poverty Level', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Retail Sales per Capita', 'Land Area (Square Miles)',
       'Population per Square Mile', '% Person under 5 years',
       '% Persons under 18 years', '% Persons 65 and older',
       '% Female Persons', '% White', '% Black African', '% Asian',
       '% Hispanic', '('Votes', ' No Preference')',
       '('Votes', ' Uncommitted')', '('Votes', 'Ben Carson')',
       '('Votes', 'Bernie Sanders')', '('Votes', 'Carly Fiorina')',
       '('Votes', 'Chris Christie')', '('Votes', 'Donald Trump')',
       '('Votes', 'Hillary Clinton')', '('Votes', 'Jeb Bush')',
       '('Votes', 'John Kasich')', '('Votes', 'Marco Rubio')',
       '('Votes', "Martin O'Malley")', '('Votes', 'Mike Huckabee')',
       '('Votes', 'Rand Paul')', '('Votes', 'Rick Santorum')',
       '('Votes', 'Ted Cruz')'],
      dtype='object')

In [7]:
df_clean = df.drop(columns=["('Votes', ' No Preference')", "('Votes', ' Uncommitted')","('Votes', 'Ted Cruz')", "('Votes', 'Ben Carson')",
                           "('Votes', 'Hillary Clinton')", "('Votes', 'Carly Fiorina')", "('Votes', 'Chris Christie')", "('Votes', 'Donald Trump')"
                            ])
df_clean.head()

,2010 Population,% Foreign Born,Median Household Income,Below Poverty Level,% Black-owned Firms,% Asian-owned Firms,% Hispanic-owned Firms,% Women-owned Firms,Retail Sales per Capita,Land Area (Square Miles),...,% Asian,% Hispanic,"('Votes', 'Bernie Sanders')","('Votes', 'Jeb Bush')","('Votes', 'John Kasich')","('Votes', 'Marco Rubio')","('Votes', ""Martin O'Malley"")","('Votes', 'Mike Huckabee')","('Votes', 'Rand Paul')","('Votes', 'Rick Santorum')"
0,54571,1.6,53682,12.1,15.2,1.3,0.7,31.7,12003,594.44,...,1.1,2.7,544,0,421,1785,0,0,0,0
1,182265,3.6,50221,13.9,2.7,1.0,1.3,27.3,17166,1589.78,...,0.9,4.6,2694,0,2987,9703,0,0,0,0
2,27457,2.9,32911,26.7,0.0,0.0,0.0,27.0,6334,884.88,...,0.5,4.5,222,0,123,498,0,0,0,0
3,22915,1.2,36447,18.1,14.9,0.0,0.0,0.0,5804,622.58,...,0.2,2.1,246,0,84,444,0,0,0,0
4,57322,4.3,44145,15.8,0.0,0.0,0.0,23.2,5622,644.78,...,0.3,8.7,395,0,337,1843,0,0,0,0

In [8]:
df_cleaner = df_clean.drop(columns=["('Votes', 'Jeb Bush')","('Votes', 'John Kasich')" , "('Votes', 'Marco Rubio')", "('Votes', 'Mike Huckabee')",
       "('Votes', 'Rand Paul')", "('Votes', 'Rick Santorum')" ])
df_cleaner.head()

,2010 Population,% Foreign Born,Median Household Income,Below Poverty Level,% Black-owned Firms,% Asian-owned Firms,% Hispanic-owned Firms,% Women-owned Firms,Retail Sales per Capita,Land Area (Square Miles),...,% Person under 5 years,% Persons under 18 years,% Persons 65 and older,% Female Persons,% White,% Black African,% Asian,% Hispanic,"('Votes', 'Bernie Sanders')","('Votes', ""Martin O'Malley"")"
0,54571,1.6,53682,12.1,15.2,1.3,0.7,31.7,12003,594.44,...,6.0,25.2,13.8,51.4,77.9,18.7,1.1,2.7,544,0
1,182265,3.6,50221,13.9,2.7,1.0,1.3,27.3,17166,1589.78,...,5.6,22.2,18.7,51.2,87.1,9.6,0.9,4.6,2694,0
2,27457,2.9,32911,26.7,0.0,0.0,0.0,27.0,6334,884.88,...,5.7,21.2,16.5,46.6,50.2,47.6,0.5,4.5,222,0
3,22915,1.2,36447,18.1,14.9,0.0,0.0,0.0,5804,622.58,...,5.3,21.0,14.8,45.9,76.3,22.1,0.2,2.1,246,0
4,57322,4.3,44145,15.8,0.0,0.0,0.0,23.2,5622,644.78,...,6.1,23.6,17.0,50.5,96.0,1.8,0.3,8.7,395,0

In [9]:
target = df_cleaner["('Votes', 'Bernie Sanders')"]
target_names = ["Votes"]

In [10]:
data = df_cleaner.drop("('Votes', 'Bernie Sanders')", axis=1)
feature_names = data.columns
data.head()

,2010 Population,% Foreign Born,Median Household Income,Below Poverty Level,% Black-owned Firms,% Asian-owned Firms,% Hispanic-owned Firms,% Women-owned Firms,Retail Sales per Capita,Land Area (Square Miles),Population per Square Mile,% Person under 5 years,% Persons under 18 years,% Persons 65 and older,% Female Persons,% White,% Black African,% Asian,% Hispanic,"('Votes', ""Martin O'Malley"")"
0,54571,1.6,53682,12.1,15.2,1.3,0.7,31.7,12003,594.44,91.8,6.0,25.2,13.8,51.4,77.9,18.7,1.1,2.7,0
1,182265,3.6,50221,13.9,2.7,1.0,1.3,27.3,17166,1589.78,114.6,5.6,22.2,18.7,51.2,87.1,9.6,0.9,4.6,0
2,27457,2.9,32911,26.7,0.0,0.0,0.0,27.0,6334,884.88,31.0,5.7,21.2,16.5,46.6,50.2,47.6,0.5,4.5,0
3,22915,1.2,36447,18.1,14.9,0.0,0.0,0.0,5804,622.58,36.8,5.3,21.0,14.8,45.9,76.3,22.1,0.2,2.1,0
4,57322,4.3,44145,15.8,0.0,0.0,0.0,23.2,5622,644.78,88.9,6.1,23.6,17.0,50.5,96.0,1.8,0.3,8.7,0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [12]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.005714285714285714

In [13]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.007142857142857143

In [14]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.06526633987836132, '2010 Population'),
 (0.06441479725900895, 'Land Area (Square Miles)'),
 (0.06398509314626559, 'Retail Sales per Capita'),
 (0.06304266306919101, 'Population per Square Mile'),
 (0.06231724405616126, 'Median Household Income'),
 (0.060161032842379836, 'Below Poverty Level'),
 (0.059644623208983664, '% Hispanic'),
 (0.059537848636355646, '% Persons 65 and older'),
 (0.059007703061629516, '% Female Persons'),
 (0.058766622501702254, '% White'),
 (0.058040057795942596, '% Persons under 18 years'),
 (0.05600204913772293, '% Foreign Born'),
 (0.05552484168237551, '% Black African'),
 (0.054109642112717085, '% Person under 5 years'),
 (0.048177218032120016, '% Asian'),
 (0.047513127998182636, '% Women-owned Firms'),
 (0.021029251917163504, '% Hispanic-owned Firms'),
 (0.020673558552015466, '% Black-owned Firms'),
 (0.019194757578266455, '% Asian-owned Firms'),
 (0.0035915275334546803, '(\'Votes\', "Martin O\'Malley")')]